services:
  # Warehousing
  postgres:
    image: "postgres:17"
    container_name: devops_insight_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Data lake
  minio:
    image: "minio/minio:latest"
    container_name: devops_insight_minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Spark
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: devops_insights_spark_master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" # For ui
      - "7077:7077" # For spark master
    environment:
      - SPARK_MODE=master
    volumes:
      - ./pipelines:/opt/bitnami/spark/pipelines
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/config

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: devops_insights_spark_worker
    command: bin/spark-class org.apache.spark.deply.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./pipelines:/opt/bitnami/spark/pipelines
      - ./data:/opt/bitnami/spark/data
      - ./config:/opt/bitnami/spark/config

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_insights_app
    depends_on:
      - postgres
      - minio
      - spark-master
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      - MINIO_ENDPOINT_URL=http://minio:9000
      - SPARK_MASTER_URL=spark://spark-master:7077

volumes:
  postgres_data:
  minio_data:
